---
include:
  - board: nice_nano_v2
    shield: enki42_left
  - board: nice_nano_v2
    shield: enki42_right
  - board: nice_nano_v2
    shield: enki42_dongle
  - board: nice_nano_v2
    shield: settings_reset
